sudo: false
language: python
git:
  depth: 3
python:
  # First python version in this list is the default for matrix.include
  # - "3.7"
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"
env:
  matrix:
    - EVM_EMACS=emacs-26.1-travis
  global:
  # Turn on --use-mirrors option everywhere (even in tox):
  - PIP_USE_MIRRORS=t
matrix:
  include:
    - env: EVM_EMACS=emacs-24.4-travis
    - env: EVM_EMACS=emacs-24.5-travis
    - env: EVM_EMACS=emacs-25.1-travis
    - env: EVM_EMACS=emacs-25.2-travis
    - env: EVM_EMACS=emacs-25.3-travis

before_install:
  - pip install -q virtualenv tox tox-travis
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install $EVM_EMACS --use --skip
  - cask
  - make before-test
script:
  make travis-ci
